const {
  GiRetroController,
  GiJoystick,
  GiGamepad,
  GiConsoleController,
  GiProcessor,
  GiCircuitry,
  GiFiles,
  GiScrollUnfurled,
  GiSpiderWeb,
  GiElectric,
  GiShinyApple,
  GiSave,
  GiOpenFolder,
  GiLockedChest,
  GiSettingsKnobs,
  GiWireCoil,
  GiLaserBurst,
  GiBattleGear,
  GiProgression,
  GiLifeSupport,
  GiCrossedSwords,
  GiFireDash,
  GiRadarDish,
  GiArtificialIntelligence,
  GiTechnoHeart,
  GiNetworkBars,
  GiNestedHexagons,
  GiHamburgerMenu,
  GiRollingEnergy,
  GiCrystalBars,
  GiUpgrade,
  GiMagnetBlast,
  GiSplitCross,
  GiPlainCircle,
  GiLightningTrio,
  GiLadybug,
  GiMicrochip,
  GiServerRack,
  GiNotebook,
  GiArrowDunk,
  GiSandsOfTime,
} = require("react-icons/gi");
const { MdFileUnknown } = require("react-icons/md");

module.exports.iconMap = {
  ".babel.config.js": GiProgression,
  ".babelrc": GiConsoleController,
  ".babelrc.js": GiRadarDish,
  ".commitlintrc": GiBattleGear,
  ".editorconfig": GiShinyApple,
  ".env.development": GiJoystick,
  ".env.local": GiRollingEnergy,
  ".env.production": GiRetroController,
  ".env.test": GiArtificialIntelligence,
  ".eslintcache": GiPlainCircle,
  ".eslintrc.cjs": GiLifeSupport,
  ".eslintrc.js": GiOpenFolder,
  ".gitattributes": GiFireDash,
  ".gitmodules": GiMicrochip,
  ".n": GiElectric,
  ".npmrc.cjs": GiRetroController,
  ".nvmrc": GiCircuitry,
  ".prettierignore": GiSplitCross,
  ".prettierrc.cjs": GiElectric,
  ".stylelintrc": GiGamepad,
  ".tool-versions": GiArtificialIntelligence,
  ".webpack.config.js": GiHamburgerMenu,
  ".yarnrc.yml": GiSandsOfTime,
  Dockerfile: GiFireDash,
  Makefile: GiLifeSupport,
  asp: GiTechnoHeart,
  bash: GiMagnetBlast,
  browserslistrc: GiGamepad,
  c: GiShinyApple,
  cc: GiSplitCross,
  cfg: GiNotebook,
  cmd: GiArrowDunk,
  conf: GiCircuitry,
  config: GiRetroController,
  cpp: GiHamburgerMenu,
  cs: GiProcessor,
  css: GiSpiderWeb,
  csv: GiJoystick,
  csx: GiMagnetBlast,
  cxx: GiBattleGear,
  dart: GiLaserBurst,
  dockerignore: GiNetworkBars,
  dotenv: GiRollingEnergy,
  ejs: GiLockedChest,
  env: GiOpenFolder,
  eslintignore: GiUpgrade,
  fish: GiArrowDunk,
  gem: GiNestedHexagons,
  gitignore: GiFireDash,
  gitkeep: GiUpgrade,
  go: GiArrowDunk,
  graphql: GiWireCoil,
  h: GiNotebook,
  hh: GiLaserBurst,
  hpp: GiBattleGear,
  htm: GiElectric,
  html: GiMagnetBlast,
  hxx: GiLifeSupport,
  ini: GiSandsOfTime,
  ipynb: GiOpenFolder,
  java: GiScrollUnfurled,
  js: GiElectric,
  jsconfig: GiCircuitry,
  json: GiServerRack,
  json5: GiLaserBurst,
  jsonc: GiLifeSupport,
  jsp: GiFiles,
  jsx: GiLifeSupport,
  kt: GiServerRack,
  kts: GiSettingsKnobs,
  less: GiFireDash,
  lock: GiLockedChest,
  log: GiShinyApple,
  m: GiJoystick,
  markdown: GiJoystick,
  md: GiSpiderWeb,
  mdx: GiGamepad,
  mm: GiElectric,
  npmignore: GiRadarDish,
  npmrc: GiRollingEnergy,
  php: GiLockedChest,
  phtml: GiLifeSupport,
  postcss: GiServerRack,
  prettierrc: GiRetroController,
  properties: GiArrowDunk,
  ps1: GiScrollUnfurled,
  psd: GiJoystick,
  psm1: GiArtificialIntelligence,
  psql: GiNotebook,
  pug: GiNetworkBars,
  py: GiCrystalBars,
  r: GiArtificialIntelligence,
  rb: GiSplitCross,
  rs: GiScrollUnfurled,
  rst: GiFiles,
  sass: GiTechnoHeart,
  scss: GiLockedChest,
  sh: GiProgression,
  sql: GiRollingEnergy,
  sqlite: GiTechnoHeart,
  styl: GiSpiderWeb,
  svelte: GiScrollUnfurled,
  swift: GiSave,
  toml: GiRetroController,
  ts: GiArtificialIntelligence,
  tsconfig: GiNetworkBars,
  tsv: GiOpenFolder,
  tsx: GiRollingEnergy,
  txt: GiMicrochip,
  vue: GiCrystalBars,
  xml: GiGamepad,
  yaml: GiFiles,
  "yarn.lock": GiLightningTrio,
  yml: GiProcessor,
  zsh: GiTechnoHeart,
  ".changeset": GiFiles,
  ".github": GiLadybug,
  ".gitlab": GiMagnetBlast,
  ".husky": GiLockedChest,
  ".storybook": GiSettingsKnobs,
  ".turbo": GiElectric,
  ".vscode": GiSettingsKnobs,
  api: GiNestedHexagons,
  apps: GiMicrochip,
  assets: GiServerRack,
  bin: GiElectric,
  build: GiCrystalBars,
  cli: GiCrossedSwords,
  components: GiTechnoHeart,
  config: GiShinyApple,
  configurations: GiMicrochip,
  constants: GiNotebook,
  controllers: GiTechnoHeart,
  core: GiGamepad,
  database: GiNotebook,
  dist: GiServerRack,
  docs: GiGamepad,
  e2e: GiUpgrade,
  environments: GiSplitCross,
  examples: GiShinyApple,
  fixtures: GiCrossedSwords,
  functions: GiSettingsKnobs,
  helpers: GiArtificialIntelligence,
  hooks: GiOpenFolder,
  i18n: GiLifeSupport,
  icons: GiSplitCross,
  images: GiLadybug,
  layouts: GiLifeSupport,
  lib: GiScrollUnfurled,
  locales: GiLaserBurst,
  middleware: GiJoystick,
  migrations: GiCrossedSwords,
  models: GiArtificialIntelligence,
  mutations: GiArrowDunk,
  node_modules: GiPlainCircle,
  packages: GiShinyApple,
  pages: GiSplitCross,
  public: GiCircuitry,
  queries: GiCircuitry,
  resolvers: GiTechnoHeart,
  schemas: GiLaserBurst,
  scripts: GiLockedChest,
  services: GiCrystalBars,
  shared: GiBattleGear,
  snapshots: GiCrystalBars,
  src: GiMagnetBlast,
  store: GiLockedChest,
  storybook: GiMagnetBlast,
  stubs: GiOpenFolder,
  styles: GiElectric,
  test: GiElectric,
  "test-utils": GiNotebook,
  tests: GiFiles,
  theme: GiScrollUnfurled,
  tools: GiSave,
  types: GiNotebook,
  utils: GiProcessor,
  vendor: GiCrossedSwords,
  clojure: GiRollingEnergy,
  cmake: GiMagnetBlast,
  cpp: GiNetworkBars,
  crystal: GiSandsOfTime,
  csharp: GiProgression,
  css: GiSettingsKnobs,
  dart: GiElectric,
  docker: GiElectric,
  dotnet: GiLaserBurst,
  elixir: GiLightningTrio,
  erlang: GiNotebook,
  fsharp: GiArrowDunk,
  go: GiGamepad,
  graphql: GiRetroController,
  groovy: GiSettingsKnobs,
  haskell: GiServerRack,
  html: GiFireDash,
  ini: GiLifeSupport,
  java: GiCircuitry,
  javascript: GiFireDash,
  json: GiSplitCross,
  json5: GiNotebook,
  jsonc: GiOpenFolder,
  kotlin: GiNotebook,
  lua: GiPlainCircle,
  makefile: GiWireCoil,
  markdown: GiOpenFolder,
  nim: GiArtificialIntelligence,
  perl: GiSandsOfTime,
  php: GiLaserBurst,
  plaintext: GiLifeSupport,
  powershell: GiFireDash,
  python: GiPlainCircle,
  r: GiArtificialIntelligence,
  reason: GiNotebook,
  rescript: GiLifeSupport,
  ruby: GiLaserBurst,
  rust: GiArrowDunk,
  scala: GiCrossedSwords,
  shellscript: GiScrollUnfurled,
  swift: GiNotebook,
  tsx: GiOpenFolder,
  typescript: GiPlainCircle,
  vb: GiMicrochip,
  yaml: GiLaserBurst,
  close: GiHamburgerMenu,
  closeAll: GiNotebook,
  closeTerminal: GiMagnetBlast,
  commentLine: GiServerRack,
  compareWithSaved: GiLifeSupport,
  convertToArrowFunction: GiNetworkBars,
  copy: GiRadarDish,
  cut: GiMicrochip,
  debugStart: GiMagnetBlast,
  debugStepInto: GiNestedHexagons,
  debugStepOut: GiHamburgerMenu,
  debugStepOver: GiHamburgerMenu,
  debugStop: GiLaserBurst,
  evaluateExpression: GiJoystick,
  extractMethod: GiSettingsKnobs,
  find: GiGamepad,
  formatDocument: GiPlainCircle,
  gitClone: GiUpgrade,
  gitCommit: GiLightningTrio,
  gitPull: GiCircuitry,
  gitPush: GiLaserBurst,
  goToDefinition: GiElectric,
  goToImplementation: GiElectric,
  goToTypeDefinition: GiPlainCircle,
  newFile: GiJoystick,
  newFolder: GiHamburgerMenu,
  newTerminal: GiSpiderWeb,
  openFile: GiNetworkBars,
  openTerminal: GiLifeSupport,
  organizeImports: GiPlainCircle,
  paste: GiFiles,
  peekDefinition: GiBattleGear,
  redo: GiRetroController,
  refactor: GiCrystalBars,
  renameSymbol: GiArtificialIntelligence,
  replace: GiCrystalBars,
  revealInExplorer: GiLaserBurst,
  runBuildTask: GiRetroController,
  runExtension: GiRollingEnergy,
  runTask: GiScrollUnfurled,
  runTestTask: GiFiles,
  save: GiWireCoil,
  saveAll: GiElectric,
  showReferences: GiConsoleController,
  splitTerminal: GiArrowDunk,
  toggleBreakpoint: GiShinyApple,
  toggleComment: GiJoystick,
  toggleDebug: GiLockedChest,
  toggleExplorer: GiRollingEnergy,
  toggleExtensions: GiConsoleController,
  togglePanel: GiProgression,
  toggleSCM: GiFireDash,
  toggleSearch: GiFiles,
  toggleSidebar: GiMagnetBlast,
  toggleTerminal: GiPlainCircle,
  uncommentLine: GiLaserBurst,
  undo: GiUpgrade,
  error: GiLaserBurst,
  warning: GiJoystick,
  info: GiUpgrade,
  success: GiRetroController,
  running: GiSave,
  paused: GiNotebook,
  passed: GiRetroController,
  failed: GiSettingsKnobs,
  pending: GiNetworkBars,
  skipped: GiServerRack,
  deprecated: GiLaserBurst,
  experimental: GiSettingsKnobs,
  beta: GiArrowDunk,
  alpha: GiRetroController,
  todo: GiArtificialIntelligence,
  bisect: GiTechnoHeart,
  branch: GiProcessor,
  cherryPick: GiRollingEnergy,
  clone: GiNestedHexagons,
  commit: GiConsoleController,
  fetch: GiJoystick,
  git: GiSpiderWeb,
  gitAdded: GiBattleGear,
  gitConflict: GiRadarDish,
  gitCopied: GiSettingsKnobs,
  gitDeleted: GiSandsOfTime,
  gitIgnored: GiNotebook,
  gitModified: GiWireCoil,
  gitRenamed: GiPlainCircle,
  gitStaged: GiConsoleController,
  gitUnstaged: GiLightningTrio,
  gitUntracked: GiProcessor,
  incomingChanges: GiWireCoil,
  log: GiArrowDunk,
  merge: GiNetworkBars,
  outgoingChanges: GiWireCoil,
  pullRequest: GiRollingEnergy,
  rebase: GiNetworkBars,
  revert: GiBattleGear,
  squash: GiSandsOfTime,
  stash: GiJoystick,
  sync: GiLadybug,
  tag: GiLockedChest,
  fileHome: GiPlainCircle,
  fileRoot: GiLaserBurst,
  fileWorkspace: GiRadarDish,
  folderHome: GiCrossedSwords,
  folderRoot: GiSpiderWeb,
  folderWorkspace: GiFireDash,
  symbolBoolean: GiLifeSupport,
  symbolClass: GiWireCoil,
  symbolConstant: GiLockedChest,
  symbolEnum: GiScrollUnfurled,
  symbolEvent: GiLifeSupport,
  symbolFunction: GiElectric,
  symbolInterface: GiCrossedSwords,
  symbolMethod: GiServerRack,
  symbolModule: GiNotebook,
  symbolNumber: GiRadarDish,
  symbolProperty: GiShinyApple,
  symbolString: GiRetroController,
  symbolVariable: GiElectric,
};
